import type { Candidate } from "@/lib/types";

export const mockCandidates: Candidate[] = [
  {
    id: "cand-001",
    name: "张三",
    position: "管培生",
    school: "贵州大学",
    background: "电子信息硕士，有 AI 应用项目经验",
    stage: "二面",
    status: "待安排",
    result: "一面通过",
    feedback: "表达清晰，项目经历和岗位有一定匹配",
    interviewTime: "2026-05-24 14:00",
    owner: "HR-小王",
    nextAction: "安排二面面试官",
    aiSummary: "一面反馈较好，下一步需要确认二面安排。",
    confidence: 0.86,
    sourceText: "HR-小王：这是管培生候选人张三的简历，贵州大学电子信息硕士，有 AI 应用项目经验。",
    createdAt: "2026-05-21T09:20:00.000Z",
    updatedAt: "2026-05-21T10:10:00.000Z"
  },
  {
    id: "cand-002",
    name: "李四",
    position: "AI 应用工程师",
    school: "西南交通大学",
    background: "计算机硕士，做过 RAG 问答和数据看板",
    stage: "已淘汰",
    status: "未通过",
    result: "未通过",
    feedback: "项目经历偏弱，系统设计表达不够清晰",
    interviewTime: "2026-05-20 16:00",
    owner: "面试官-陈老师",
    nextAction: "归档并同步候选人状态",
    aiSummary: "技术匹配度不足，建议不进入下一轮。",
    confidence: 0.82,
    sourceText: "面试官-陈老师：李四不太合适，沟通表达一般，项目经历偏弱，建议淘汰。",
    createdAt: "2026-05-20T03:30:00.000Z",
    updatedAt: "2026-05-21T08:40:00.000Z"
  },
  {
    id: "cand-003",
    name: "王敏",
    position: "测试工程师",
    school: "重庆邮电大学",
    background: "熟悉接口测试和自动化测试",
    stage: "一面",
    status: "待反馈",
    result: null,
    feedback: "已完成一面，面试官尚未给出结论",
    interviewTime: "2026-05-21 15:30",
    owner: "HR-小周",
    nextAction: "提醒面试官补充反馈",
    aiSummary: "一面已完成，当前卡点是反馈未回收。",
    confidence: 0.78,
    sourceText: "HR-小周：王敏今天下午完成测试工程师一面，麻烦面试官稍后同步反馈。",
    createdAt: "2026-05-21T01:15:00.000Z",
    updatedAt: "2026-05-21T07:55:00.000Z"
  },
  {
    id: "cand-004",
    name: "赵磊",
    position: "产品运营",
    school: "四川大学",
    background: "有校园活动和数据运营经验",
    stage: "简历筛选",
    status: "待跟进",
    result: null,
    feedback: "简历信息完整，需确认可面试时间",
    interviewTime: null,
    owner: "HR-小王",
    nextAction: "联系候选人确认一面时间",
    aiSummary: "简历匹配产品运营岗位，等待 HR 发起沟通。",
    confidence: 0.74,
    sourceText: "HR-小王：赵磊投递产品运营，四川大学，有校园活动和数据运营经验。",
    createdAt: "2026-05-21T02:40:00.000Z",
    updatedAt: "2026-05-21T02:45:00.000Z"
  },
  {
    id: "cand-005",
    name: "陈雨",
    position: "AI 应用工程师",
    school: "电子科技大学",
    background: "参与过智能客服和模型评测平台",
    stage: "终面",
    status: "待安排",
    result: "二面通过",
    feedback: "工程落地经验较强，沟通稳定",
    interviewTime: "2026-05-23 10:30",
    owner: "HR-小林",
    nextAction: "安排业务负责人终面",
    aiSummary: "已通过二面，优先推进终面安排。",
    confidence: 0.9,
    sourceText: "面试官-刘老师：陈雨二面通过，工程落地经验不错，可以安排终面。",
    createdAt: "2026-05-19T06:00:00.000Z",
    updatedAt: "2026-05-21T06:20:00.000Z"
  },
  {
    id: "cand-006",
    name: "周航",
    position: "管培生",
    school: "云南大学",
    background: "商科背景，参与过校企项目",
    stage: "Offer",
    status: "已通过",
    result: "终面通过",
    feedback: "综合素质较好，稳定性强",
    interviewTime: "2026-05-19 11:00",
    owner: "HR-小周",
    nextAction: "准备 Offer 沟通",
    aiSummary: "终面已通过，进入 Offer 沟通阶段。",
    confidence: 0.88,
    sourceText: "业务负责人：周航终面通过，可以进入 Offer 沟通。",
    createdAt: "2026-05-18T09:10:00.000Z",
    updatedAt: "2026-05-20T11:25:00.000Z"
  },
  {
    id: "cand-007",
    name: "胡佳",
    position: "测试工程师",
    school: "成都理工大学",
    background: "有 App 测试和缺陷管理经验",
    stage: "二面",
    status: "待跟进",
    result: "一面通过",
    feedback: "基础扎实，但自动化深度需要二面确认",
    interviewTime: "2026-05-22 19:00",
    owner: "HR-小林",
    nextAction: "确认二面会议链接",
    aiSummary: "一面通过，二面重点确认自动化能力。",
    confidence: 0.81,
    sourceText: "面试官-杨老师：胡佳基础还可以，建议二面再看自动化深度。",
    createdAt: "2026-05-20T05:05:00.000Z",
    updatedAt: "2026-05-21T05:45:00.000Z"
  },
  {
    id: "cand-008",
    name: "林可",
    position: "产品运营",
    school: null,
    background: "有内容运营和用户分层经验",
    stage: "一面",
    status: "已通过",
    result: "一面通过",
    feedback: "对用户增长指标理解较好",
    interviewTime: "2026-05-20 14:30",
    owner: "面试官-李老师",
    nextAction: "安排二面",
    aiSummary: "产品运营思路清楚，建议进入二面。",
    confidence: 0.84,
    sourceText: "面试官-李老师：林可对用户增长指标理解较好，可以进二面。",
    createdAt: "2026-05-19T02:00:00.000Z",
    updatedAt: "2026-05-20T08:30:00.000Z"
  },
  {
    id: "cand-009",
    name: "马宁",
    position: "AI 应用工程师",
    school: "贵州大学",
    background: "本科，做过简历解析小工具",
    stage: "待确认",
    status: "待反馈",
    result: null,
    feedback: "群聊信息不完整，需要 HR 复核岗位和轮次",
    interviewTime: null,
    owner: "HR-小王",
    nextAction: "补充简历和面试记录",
    aiSummary: "信息不完整，需人工确认后再推进。",
    confidence: 0.62,
    sourceText: "HR-小王：马宁的资料不完整，先放待确认。",
    createdAt: "2026-05-21T04:10:00.000Z",
    updatedAt: "2026-05-21T04:15:00.000Z"
  },
  {
    id: "cand-010",
    name: "孙琪",
    position: "管培生",
    school: "西南财经大学",
    background: "数据分析方向，实习做过经营报表",
    stage: "简历筛选",
    status: "待安排",
    result: null,
    feedback: "简历初筛通过，等待安排一面",
    interviewTime: null,
    owner: "HR-小周",
    nextAction: "发送一面邀约",
    aiSummary: "初筛通过，待安排一面。",
    confidence: 0.79,
    sourceText: "HR-小周：孙琪管培生简历初筛通过，安排一面。",
    createdAt: "2026-05-21T06:30:00.000Z",
    updatedAt: "2026-05-21T06:35:00.000Z"
  }
];
